apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deploygroups.paasta.yelp.com
spec:
  group: paasta.yelp.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: deploygroups
    singular: deploygroup
    kind: DeployGroup
    shortNames:
    - dg
  validation:
    openAPIV3Schema:
      type: object
      properties:
        service:
          type: string
        deploy_group:
          type: string
        git_sha:
          type: string
